spring:
  application:
    name: spring-security
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: Karen@123**
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 2040

security:
  jwt:
    exception:
      minutes: 30

    secret:
      key: VGhpcyBpcyBteSBzZWNyZXQga2V5IFRyeSBoYWNraW5nIGl0IGFuZCB5b3Ugd2lsbCBnZXQgaW4gYSBob3QgbWVzcw==